language: java

sudo: false

install:
  # install without testing
  - mvn install -U -DskipTests -B -V -fae -q

script:
  # execute unit and integration tests
  - mvn -e test verify -B
  # on java 8 run a javadoc build to check for errors
  - if [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
         mvn javadoc:javadoc;
    fi

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

os:
  - linux
  # - osx

matrix:
  fast_finish: true

cache:
  directories:
  - $HOME/.m2
  
