language: java

sudo: false

install:
  # install without testing
  - mvn install -Dmaven.test.skip=true -B -V -fae -q -T2

script:
  # execute tests
  - mvn -e verify -B

after_success:
  # eg. generate code coverage report
  # - mvn -B -e -fae clean verify jacoco:report coveralls:report

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

os:
  - linux
  # - osx

matrix:
  fast_finish: true

cache:
  directories:
  - $HOME/.m2
  
